# Generated by Django 5.2.1 on 2025-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_gelatoflavour"),
    ]

    operations = [
        migrations.CreateModel(
            name="GelatoSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
    ]
