version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
    static_volume:
    pgdata: